services:
  app:
    build: ./B2C-Store
    image: minhhoangnguyen22023230/fullstack:latest
    container_name: b2c
    working_dir: /app
    command: pnpm turbo start
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
      - "3001:3001"
  
  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./certbot/admin:/var/admin/certbot
    depends_on:
      - app

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email hoangsaga123@gmail.com -d b2cstores.pw -d www.b2cstores.pw --agree-tos

  certbot-admin:
    container_name: certbot-admin
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/admin:/var/admin/certbot
    command: certonly --webroot -w /var/admin/certbot --force-renewal --email hoangsaga123@gmail.com -d admin.b2cstores.pw --agree-tos