services:
  backend:
    build: ./B2C-Store
    image: minhhoangnguyen22023230/fullstack:latest
    container_name: b2c
    working_dir: /app
    command: pnpm turbo start
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
      - "3001:3001"
