import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./slideDown.css";
import Provider from "@/app/_trpc/Provider";
import ClientLayout from "./clientLayout";
import ThemeProvider from "./ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* Move font classes to html so .light/.dark is not overwritten on body */}
      <body>
        <ThemeProvider>
          <div className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <Provider><ClientLayout>{children}</ClientLayout></Provider>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
